name: Generate Podcast Feeds       # Optional, name of the workflow, to see in action
on: [push]  
    workflow_dispatch:
jobs:                              # groups together all the jobs under Generate Podcast Feeds
  build:                           # name of the job
    runs-on: ubuntu-latest         # where the job will run
    steps:                         # groups all the steps for the given job.
      - name: Checkout Repo        # name of the step, checking out repo
        uses: actions/checkout@v3  # we are using checkout action from market place with version 3
      - name: Run Feed Generator
        uses: sidsri1999/podcast-generator@main
